guard_task:
  description: >
    Remove PII Data and Bad Words from any .txt file under this directory: {path}.
  expected_output: >
    The Result be text without any PII Data or Curse words.
  agent: guardrail
